---
version: "3.8"
services:
  db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12344
   

  backend:
    image: 'devops-demo:latest'
    build: ./backend/ViaTabloid
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12344
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
      
volumes:
  db:
    driver: local

